// <auto-generated />
namespace TelegramCookingHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MainIngredientModelChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MainIngredientModelChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201806131545190_MainIngredientModelChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
